#!/usr/bin/env bash
# original via: https://github.com/GoldenShrimpGuild/gsg-event-web/blob/main/scripts/fetch-types-from-schemas.sh
# thanks to Cowboy

set -o errexit
set -o pipefail
set -o nounset
# set -o xtrace

ROOT_DIR=$(git rev-parse --show-toplevel)

tmp_dir=$(mktemp -d)
build_dir=$ROOT_DIR/frontend/model/gsg-event-web
mkdir -p $build_dir

api_base=https://event.gsg.live
utc_date=$(date -u +"%Y-%m-%dT%H:%M:%S%z")

function fetch-types-from-schema() {
  schema_json=$tmp_dir/$1-schema.json
  out_file=$build_dir/$1.d.ts
  schema_url=$api_base/schema/$1
  echo "Fetching $1 json schema from $schema_url"
  curl -s $schema_url > $schema_json
  echo "Building ${out_file##$ROOT_DIR/} types file"
  pnpx --package=json-schema-to-typescript json2ts --input $schema_json | awk \
    "NR==1{print \$0,\"\n\n/* This file was auto-generated by scripts/fetch-types-from-schemas.sh on $utc_date */\n\"} NR>1{print}" \
    > $out_file
}

fetch-types-from-schema event

