name: Deploy ShrampyDev

on:
  push:
    branches: [main]

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install and prepare doctl
        uses: digitalocean/action-doctl@v2.5.1
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Install doctl serverless support
        run: doctl serverless install
      - name: Connect to serverless namespace
        run: doctl serverless connect ${{ vars.DO_SERVERLESS_NAMESPACE }}
      - name: Decrypt project.yml
        run: tools/decrypt_project_yml.sh
        env:
          PROJECT_YML_CRYPT_KEY: ${{ secrets.PROJECT_YML_CRYPT_KEY }}
      - name: Deploy shrampy-dev
        run: doctl serverless deploy . --include shrampy-dev
