name: Deploy ShrampyBot-Prod (Go)

on:
  push:
    tags: [ 'v*.*.*' ]

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install and prepare doctl
        uses: digitalocean/action-doctl@v2.5.1
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Install doctl serverless support
        run: doctl serverless install
      - name: Connect to serverless namespace
        run: doctl serverless connect ${{ vars.DO_SERVERLESS_NAMESPACE }}
      - name: Decrypt project.yml
        run: tools/decrypt_project_yml.sh
        env:
          PROJECT_YML_CRYPT_KEY: ${{ secrets.PROJECT_YML_CRYPT_KEY }}
      - name: Deploy shrampybot-prod
        run: doctl serverless deploy . --include shrampybot-prod --remote-build
