name: Deploy ShrampyBot-Dev (Go)

on:
  push:
    branches: [main]

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Setup Go 1.23.4
        uses: actions/setup-go@v5
        with:
          # Semantic version range syntax or exact version of Go
          go-version: '1.23.4'
      - name: Decrypt project.yml
        run: ./decrypt_template.sh
        env:
          PROJECT_YML_CRYPT_KEY: ${{ secrets.PROJECT_YML_CRYPT_KEY }}
        working-directory: ./deploy-dev
      - name: Build shrampybot-dev
        run: sam build
        working-directory: ./deploy-dev
      - name: Deploy shrampybot-dev
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --region eu-central-1
        working-directory: ./deploy-dev
